# style name or JSON path (default "auto")
style: "tokyo-night"
#style: "nord"
# mouse support (TUI-mode only)
mouse: true
# use pager to display markdown
pager: true
# word-wrap at width
width: 85
#linenumbers
line-numbers: true
