services:
  app:
    build: .
    ports:
      - "${PORT:-5050}:5050"
    env_file:
      - .env
    environment: # optionally define in -e argument when running docker command
      API_KEY: ${API_KEY:-your_api_key_here}
      PORT: ${PORT:-5050}
      DEFAULT_VOICE: ${DEFAULT_VOICE:-es-CL-CatalinaNeural}
      DEFAULT_RESPONSE_FORMAT: ${DEFAULT_RESPONSE_FORMAT:-mp3}
      DEFAULT_SPEED: ${DEFAULT_SPEED:-1.3}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-es-CL}
      REQUIRE_API_KEY: ${REQUIRE_API_KEY:-True}
      REMOVE_FILTER: ${REMOVE_FILTER:-False}
      EXPAND_API: ${EXPAND_API:-True}
