services:
  windows:
    image: dockurr/windows
    container_name: windows11
    environment:
      VERSION: "win11"
      REGION: "en-US"
      KEYBOARD: "en-US"
      USERNAME: "bill"
      PAASSWORD: "gates"
      CPU_CORES: "4"
      RAM_SIZE: "8G"
      DISK_SIZE: "100G"
      LANGUAGE: "English"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /O:/developer/AppData/Local/Docker/win11:data
